# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - important
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
  If this is still an issue, please make sure it is up to date and if so,
  add a comment that this is still an issue to keep it open.
  Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
pulls:
  daysUntilStale: 60
  markComment: >
    This pull request has been automatically marked as stale because it has not had
     recent activity. It will be closed if no further activity occurs.
     If this is still applicable, please make sure it is up to date and if so,
     add a comment that this is still an issue to keep it open.
     Thank you for your contributions.
