coverage:
  ignore:
    - "Examples"
    - "Vendors"
    - "Tests"
  status:
    project:
      default: off
      ios:
        flags: ios
      macos:
        flags: macos
      tvos:
        flags: tvos
