source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'SDWebImage Tests'
workspace '../SDWebImage'

target 'Tests' do
  platform :ios, '8.0'
  pod 'Expecta'
  pod 'KVOController'
  pod 'SDWebImage/MapKit', :path => '../'

end

target 'Tests Mac' do
  platform :osx, '10.10'
  pod 'Expecta'
  pod 'KVOController'
  pod 'SDWebImage/MapKit', :path => '../'

end
